# Site settings
title: Iain's Technical Blog
email: iain@iain-bryson.ca
description: > # this means to ignore newlines until "baseurl:"
  Technical notes and experiences by Iain Bryson.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iainbryson.github.io" # the base hostname & protocol for your site
twitter_username: iainbryson
github_username:  iainbryson

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', '2014-11-15-welcome-to-jekyll.markdown_', 'about.md_backup', 'test-site.sh']
